POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1pa2tvIiwiaWQiOiI2NzQ1YTBhN2E2NjllYWM4NjZiYzM2OWQiLCJpYXQiOjE3MzI2MzA2MzJ9.6GglXdjcMzL0YhOgQ-n-ZDGTDfpjZIe_C8uJRxhXn-I

{
  "title": "Testing",
  "author": "Mikko Kirkanen",
  "url": "url-address"
}